### PR TITLE
"Fused Build" -> "Embed PCK"

### PR DESCRIPTION
**Pull request by halotroop2288**
To match every other platform that supports this option.

### CODE REVIEW

**Comment by c08oprkiua** [comment]
I think this should be marked as a "breaking change" for the next formal release, since the editor would now be looking for a different setting. Other than that tho, no objections from me

**Comment by halotroop2288** [comment]
~~Huh? What would break?~~

Never mind. I see the issue. Existing projects would have this setting reset to default.

**Comment by hokaze** [comment]
> I think this should be marked as a "breaking change" for the next formal release, since the editor would now be looking for a different setting. Other than that tho, no objections from me

Does the editor really need a rebuild when a template option changes?
I thought the template itself is what adds the setting to the editor once its imported, it might not need a newer editor build for the name challenge to apply if the newer template is used - but I could likely be wrong on that, probably worth checking a template with this change against the older editor to be sure.

(my main basis for thinking this is how the editor options aren't even available until you've manually ensured the templates are available to it, so I don't think the editor actually has the GUI options for each template preset - otherwise why have seperate templates at all and not pre-bundle them into the editor if you're going to be taking some of the code from them anyway. Again, could be misremembering, and it's worth checking!)

Also, even if it did break and did need a note that the user should update the editor, not just the template...in practice do people just use updated templates without updating the editor?
We've had quite a few changes which will need editor rebuilds and not just template rebuilds - like the Switch singleton used in the test suite, IIRC you can still export the project on a slightly older editor but it'll complain in the code editor because it doesn't recognise the singleton or platform-specific stuff for the virtual keyboard.

**Comment by halotroop2288** [comment]
> Does the editor really need a rebuild when a template option changes?

Yes. The options are part of the exporter code, which is built into the editor. They are loaded and can be seen even before *any* templates are installed.

**Comment by hokaze** [comment]
> Yes. The options are part of the exporter code, which is built into the editor. They are loaded and can be seen even before _any_ templates are installed.

Ah, right, I was thinking of it just dynamically adding stuff to it after the fact, but that does make sense.

And I see the bit about existing projects losing the setting and thus needing to re-enable it in the export options is indeed the big thing (by which I mean incredibly small inconvenience, but one that users would need to be made aware of in release notes)

**Review by hokaze — CHANGES_REQUESTED** [review]
Line 151 was changed to use "binary_format/embed_pck" but line 364 references "application/embed_pck", should both use the same property name.

**Comment by halotroop2288** [comment]
Good catch.

**Review by hokaze — APPROVED** [review]
Looks good to me.

And agreed that next release should have appropriate note about users needing to re-enable Embed PCK if they were previously using Fused Build

**Pull request merged**
